### PR TITLE
Delete DataOneV1

### PR DESCRIPTION
**Pull request by oxinabox**
Re https://github.com/oxinabox/DataDepsGenerators.jl/issues/67#issuecomment-432897192

### CODE REVIEW

**Comment by oxinabox** [comment]
the combining failure is because now there is one less generator and the results are different.
Semantically they are the same, but since the different providers do things like `http` vs `https` for the website that does change the reference.
So that needs to be regenerated.

**Comment by oxinabox** [comment]
while fixing this I noticed that our DataDryad generator wasn't working for DOIs, which I fixed,
and added tests.

Also I think this will fail, as I think the DataCite API is down
cf: https://twitter.com/oxinabox_frames/status/1056115555499823105
Update: yes indeed it is down.

**Comment by oxinabox** [comment]
Tests passing.
@SebastinSanty  do you want to review it?

**Comment by SebastinSanty** [comment]
Sure, I'll check

**Review by SebastinSanty — APPROVED** [review]
LGTM

**Pull request merged**
