### PR TITLE
[WIP] Bump to Julia 1.0

### PR DESCRIPTION
**Pull request by SebastinSanty**

### CODE REVIEW

**Comment by SebastinSanty** [comment]
Gosh, upgrading is so confusing.

**Comment by oxinabox** [comment]
You'll need to update the CI scripts too, or we can't see anything.

Also you'll need to add Test dependencies on DataDeps and on Test, in the Project.toml.

**Comment by SebastinSanty** [comment]
Yep, doing that. Following #pkg-usage and #upgradeathon for instructions.

**Comment by SebastinSanty** [comment]
Seems like Gumbo doesn't build on Julia 1.0. All other dependencies does.

**Comment by oxinabox** [comment]
> Seems like Gumbo doesn't build on Julia 1.0. All other dependencies does.

We'll have to wait for that then

**Comment by SebastinSanty** [comment]
What can we do till then? Also, how are you? seems you aren't online much.

**Comment by oxinabox** [comment]
Til then we can help by fixing Gumbo  -- probably not too hard.
Also some of the code quality cleanup here, and improving docs.
On the docs note I rather liked your final blog post.
It was nice to see all the PRs.

I've been away for juliacon, and then some things afterwards.

**Comment by SebastinSanty** [comment]
Gumbo is already fixed. Issues with other packages like Cascadia.jl and its dependencies. Will look into fixing that.

Yes, I'll push the cleanup part. Also, would you want a formal documentation like readthedocs for DataDeps.jl and DataDepsGenerators.jl? All what exists right now are our blogs, which is often not the best, especially for quick use.

**Comment by oxinabox** [comment]
I am happy with just stuff being put in Readme.MD
I don't think full ReadTheDocs style is useful here.

It is a simple enough package to use.

**Comment by oxinabox** [comment]
This should now be possible

**Comment by oxinabox** [comment]
Closing this in favour of #55.
I am trying to get Femtocleaner to do the work

**Pull request closed without merging**
